/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Mesto;

/**
 *
 * @author Ljilja
 */
public class KreirajKupcaForma extends javax.swing.JFrame {

    
    public KreirajKupcaForma() {
       initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiraj kupca");
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldBrojTelefona = new javax.swing.JTextField();
        jButtonKreiraj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonOdustani = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonPromeni = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonObrisi = new javax.swing.JButton();
        jButtonPromeniDugme = new javax.swing.JButton();
        jButtonOdustani1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 217, 183));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ime:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 65, 110, -1));

        jLabel2.setText("Prezime:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 108, 110, -1));

        jLabel3.setText("Broj telefona:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 153, 120, -1));

        jTextFieldIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 62, 280, -1));
        getContentPane().add(jTextFieldPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 105, 280, -1));
        getContentPane().add(jTextFieldBrojTelefona, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 150, 280, -1));

        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKreiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 200, 30));

        jLabel4.setText("Mesto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 190, 110, -1));

        jButtonOdustani.setText("Odustani");
        getContentPane().add(jButtonOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 200, 30));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 190, 280, -1));

        jButtonPromeni.setText("Sacuvaj promene");
        getContentPane().add(jButtonPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 200, 30));

        jLabelId.setText("Id:");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 25, 56, -1));
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 22, 280, -1));

        jButtonObrisi.setText("Obrisi");
        getContentPane().add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 200, 30));

        jButtonPromeniDugme.setText("Promeni");
        getContentPane().add(jButtonPromeniDugme, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 200, 30));

        jButtonOdustani1.setText("Odustani");
        getContentPane().add(jButtonOdustani1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImeActionPerformed

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKreirajActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonOdustani1;
    private javax.swing.JButton jButtonPromeni;
    private javax.swing.JButton jButtonPromeniDugme;
    private javax.swing.JComboBox<Mesto> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JTextField jTextFieldBrojTelefona;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    
public void obrisiKupcaAddActionListener(ActionListener actionListener){
    jButtonObrisi.addActionListener(actionListener);
}
   
public void kreirajKupcaAddActionListener(ActionListener actionListener){
    jButtonKreiraj.addActionListener(actionListener);
}

public void odustaniAddActionListener(ActionListener actionListener){
    jButtonOdustani.addActionListener(actionListener);
}

public void promeniAddActionListener(ActionListener actionListener){
    jButtonPromeni.addActionListener(actionListener);
}
public void promeniDugmeAddActionListener(ActionListener actionListener){
    jButtonPromeniDugme.addActionListener(actionListener);
}

public void odustani1AddActionListener(ActionListener actionListener){
    jButtonOdustani1.addActionListener(actionListener);
}


    public JButton getjButtonPromeniDugme() {
        return jButtonPromeniDugme;
    }


    public JTextField getjTextFieldBrojTelefona() {
        return jTextFieldBrojTelefona;
    }

    public JTextField getjTextFieldIme() {
        return jTextFieldIme;
    }

    public JComboBox<Mesto> getjComboBox1() {
        return jComboBox1;
    }

    public JButton getjButtonKreiraj() {
        return jButtonKreiraj;
    }

    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }

    public JButton getjButtonOdustani1() {
        return jButtonOdustani1;
    }
    public JButton getjButtonPromeni() {
        return jButtonPromeni;
    }


    public JTextField getjTextFieldPrezime() {
        return jTextFieldPrezime;
    }

    public JLabel getjLabelId() {
        return jLabelId;
    }

    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    private void dizajn() {

        Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
        Font textFont = new Font("Times New Roman", Font.BOLD, 18);
        Font dugmeFont = new Font("Times New Roman", Font.BOLD, 18);
        Font comboFont = new Font("Times New Roman", Font.PLAIN, 16);


        Color labelColor = new Color(46, 78, 31); // tamno zelena
        Color inputTextColor = new Color(43, 43, 43); // tamno siva
        Color inputBg = Color.WHITE;
        Color inputDisabledBg = new Color(200, 230, 200); // svetlo zelena za disabled
        Color dugmeEnabledBg = new Color(46, 78, 31);
        Color dugmeDisabledBg = new Color(180, 180, 180);
        Color dugmeEnabledFg = Color.WHITE;
        Color dugmeDisabledFg = new Color(80, 80, 80);


        getContentPane().setBackground(new Color(245, 245, 245));
        setSize(760, 350);
        setResizable(false);
        setLocationRelativeTo(null);


        JLabel[] labele = { jLabel1, jLabel2, jLabel3, jLabel4, jLabelId };
        for (JLabel lbl : labele) {
            lbl.setFont(labelFont);
            lbl.setForeground(labelColor);
        }


        JTextField[] polja = { jTextFieldBrojTelefona, jTextFieldId, jTextFieldIme, jTextFieldPrezime };
        for (JTextField tf : polja) {
            tf.setFont(textFont);
            tf.setBorder(BorderFactory.createLineBorder(labelColor, 2));
            tf.setOpaque(true); 
            if(tf.isEditable()) {
                tf.setBackground(inputBg);
                tf.setForeground(inputTextColor);
            } else {
                tf.setBackground(inputDisabledBg);
                tf.setForeground(inputTextColor.brighter()); 
            }
        }


        jComboBox1.setFont(comboFont);
        jComboBox1.setOpaque(true);
        if(jComboBox1.isEnabled()) {
            jComboBox1.setBackground(inputBg);
            jComboBox1.setForeground(inputTextColor);
        } else {
            jComboBox1.setBackground(inputDisabledBg);
            jComboBox1.setForeground(inputTextColor.darker());
        }


        JButton[] buttons = { jButtonKreiraj, jButtonObrisi, jButtonOdustani, jButtonOdustani1, jButtonPromeni, jButtonPromeniDugme };
        for (JButton btn : buttons) {
            btn.setFont(dugmeFont);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);
            if(btn.isEnabled()) {
                btn.setBackground(dugmeEnabledBg);
                btn.setForeground(dugmeEnabledFg);
            } else {
                btn.setBackground(dugmeDisabledBg);
                btn.setForeground(dugmeDisabledFg);
            }
        }
    }

    



}
