/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.StrSprema;

/**
 *
 * @author Ljilja
 */
public class KreirajProdavcaForma extends javax.swing.JFrame {

    /**
     * Creates new form KreirajProdavcaForma
     */
    public KreirajProdavcaForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiraj prodavca");
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldKorisnickoIme = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldLozinka = new javax.swing.JTextField();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonSacuvajIzmene = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxStepenStrSpreme = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStrSprema = new javax.swing.JTable();
        jButtonDodajStrSpremu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldInstitucija = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonDodaj = new javax.swing.JButton();
        jButtonOdustaniStrSprema = new javax.swing.JButton();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldGrad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonPrikazi = new javax.swing.JButton();
        jButtonSacuvajPromeneStrSprema = new javax.swing.JButton();
        jButtonPROMENIDUGME = new javax.swing.JButton();
        jButtonOdustani1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 217, 183));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ime:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 66, 110, -1));

        jLabel2.setText("Prezime:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 103, 110, -1));

        jLabel3.setText("Korisnicko ime:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 146, 160, -1));

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 185, 130, -1));

        jLabel5.setText("Lozinka:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 231, 140, -1));
        getContentPane().add(jTextFieldIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 63, 200, -1));
        getContentPane().add(jTextFieldPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 103, 200, -1));
        getContentPane().add(jTextFieldKorisnickoIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 143, 180, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 185, 200, -1));
        getContentPane().add(jTextFieldLozinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 231, 200, -1));

        jButtonKreiraj.setText("Kreiraj");
        getContentPane().add(jButtonKreiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 30));

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 140, 30));

        jLabelId.setText("id:");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 26, 90, -1));
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 23, 200, -1));

        jButtonSacuvajIzmene.setText("Sacuvaj promene");
        getContentPane().add(jButtonSacuvajIzmene, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 180, 30));

        jButtonObrisi.setText("Obrisi");
        getContentPane().add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Stepen strucne spreme:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 75, 220, -1));

        jPanel1.add(jComboBoxStepenStrSpreme, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 240, -1));

        jTableStrSprema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStrSprema);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 239, 620, 201));

        jButtonDodajStrSpremu.setText("Dodaj novi stepen");
        jButtonDodajStrSpremu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStrSpremuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDodajStrSpremu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 190, -1));

        jLabel10.setText("Institucija:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 210, -1));
        jPanel1.add(jTextFieldInstitucija, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 270, -1));

        jLabel7.setText("Datum sticanja (dd.MM.yyyy.):");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 20));

        jButtonDodaj.setText("Dodaj");
        jPanel1.add(jButtonDodaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 150, -1));

        jButtonOdustaniStrSprema.setText("Odustani");
        jPanel1.add(jButtonOdustaniStrSprema, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 150, -1));
        jPanel1.add(jTextFieldDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 210, -1));

        jLabel8.setText("Grad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, -1));
        jPanel1.add(jTextFieldGrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 220, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Strucna sprema prodavca");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 350, -1));

        jButtonPrikazi.setText("Prikazi");
        jPanel1.add(jButtonPrikazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 150, -1));

        jButtonSacuvajPromeneStrSprema.setText("Sacuvaj promene");
        jPanel1.add(jButtonSacuvajPromeneStrSprema, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 6, 690, 450));

        jButtonPROMENIDUGME.setText("Promeni");
        getContentPane().add(jButtonPROMENIDUGME, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 180, 30));

        jButtonOdustani1.setText("Odustani");
        getContentPane().add(jButtonOdustani1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajStrSpremuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStrSpremuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDodajStrSpremuActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOdustaniActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonDodajStrSpremu;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonOdustani1;
    private javax.swing.JButton jButtonOdustaniStrSprema;
    private javax.swing.JButton jButtonPROMENIDUGME;
    private javax.swing.JButton jButtonPrikazi;
    private javax.swing.JButton jButtonSacuvajIzmene;
    private javax.swing.JButton jButtonSacuvajPromeneStrSprema;
    private javax.swing.JComboBox<StrSprema> jComboBoxStepenStrSpreme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStrSprema;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldGrad;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldInstitucija;
    private javax.swing.JTextField jTextFieldKorisnickoIme;
    private javax.swing.JTextField jTextFieldLozinka;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonKreiraj() {
        return jButtonKreiraj;
    }
    
    public JButton getjButtonOdustani1() {
        return jButtonOdustani1;
    }

    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }

    public JComboBox<StrSprema> getjComboBox1() {
        return jComboBoxStepenStrSpreme;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public JTextField getjTextFieldIme() {
        return jTextFieldIme;
    }

    public JTextField getjTextFieldKorisnickoIme() {
        return jTextFieldKorisnickoIme;
    }

    public JTextField getjTextFieldLozinka() {
        return jTextFieldLozinka;
    }

    public JTextField getjTextFieldPrezime() {
        return jTextFieldPrezime;
    }

    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    public JLabel getjLabelId() {
        return jLabelId;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    public JButton getjButtonSacuvajIzmene() {
        return jButtonSacuvajIzmene;
    }

    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    public JButton getjButtonDodajStrSpremu() {
        return jButtonDodajStrSpremu;
    }

    public JButton getjButtonOdustaniStrSprema() {
        return jButtonOdustaniStrSprema;
    }

    public JTable getjTableStrSprema() {
        return jTableStrSprema;
    }

    public JTextField getjTextFieldDatum() {
        return jTextFieldDatum;
    }

    public JTextField getjTextFieldGrad() {
        return jTextFieldGrad;
    }

    public JTextField getjTextFieldInstitucija() {
        return jTextFieldInstitucija;
    }

    public JComboBox<StrSprema> getjComboBoxStepenStrSpreme() {
        return jComboBoxStepenStrSpreme;
    }

    public JButton getjButtonPROMENIDUGME() {
        return jButtonPROMENIDUGME;
    }

    public JButton getjButtonPrikazi() {
        return jButtonPrikazi;
    }

    public JButton getjButtonSacuvajPromeneStrSprema() {
        return jButtonSacuvajPromeneStrSprema;
    }

   
    public void promeniDugmeAddActionListener(ActionListener actionListener){
        jButtonPROMENIDUGME.addActionListener(actionListener);
    }   
    public void prikaziStrSpremaAddActionListener(ActionListener actionListener){
        jButtonPrikazi.addActionListener(actionListener);
    }    

    public void sacuvajPromeneStrSpremaAddActionListener(ActionListener actionListener){
        jButtonSacuvajPromeneStrSprema.addActionListener(actionListener);
    }

    public void odustani1AddActionListener(ActionListener actionListener){
        jButtonOdustani1.addActionListener(actionListener);
    }

    public void kreirajAddActionListener(ActionListener actionListener){
        jButtonKreiraj.addActionListener(actionListener);
    }
    public void odustaniAddActionListener(ActionListener actionListener){
        jButtonOdustani.addActionListener(actionListener);
    }

    public void obrisiAddActionListener(ActionListener actionListener){
        jButtonObrisi.addActionListener(actionListener);
    }

    public void sacuvajIzmeneAddActionListener(ActionListener actionListener){
        jButtonSacuvajIzmene.addActionListener(actionListener);
    }

    public void dodajAddActionListener(ActionListener actionListener){
        jButtonDodaj.addActionListener(actionListener);
    }
    public void odustaniStrSpremaAddActionListener(ActionListener actionListener){
        jButtonOdustaniStrSprema.addActionListener(actionListener);
    }

    public void dodajStrSpremuAddActionListener(ActionListener actionListener){
        jButtonDodajStrSpremu.addActionListener(actionListener);
    }
    
    
    private void dizajn() {
        // Fontovi
        Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
        Font textFont = new Font("Times New Roman", Font.BOLD, 18);
        Font dugmeFont = new Font("Times New Roman", Font.BOLD, 18);
        Font comboFont = new Font("Times New Roman", Font.PLAIN, 16);

        // Pozadina forme
        getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // svetlo siva
        setSize(1150, 500);
        setResizable(false);
        setLocationRelativeTo(null);

        // Pozadina panela
        jPanel1.setBackground(new java.awt.Color(220, 210, 200)); // malo tamnija ili druga nijansa

        // Labele
        JLabel[] labele = {
            jLabel1, jLabel2, jLabel3, jLabel4, jLabel5,
            jLabel6, jLabel7, jLabel8, jLabel9, jLabel10, jLabelId
        };
        java.awt.Color labelColor = new java.awt.Color(46, 78, 31); // tamna zelena
        for (JLabel lbl : labele) {
            lbl.setFont(labelFont);
            lbl.setForeground(labelColor);
        }

        // Tekstualna polja
        JTextField[] polja = {
            jTextFieldDatum, jTextFieldEmail, jTextFieldGrad, jTextFieldId,
            jTextFieldIme, jTextFieldInstitucija, jTextFieldKorisnickoIme,
            jTextFieldLozinka, jTextFieldPrezime
        };
        java.awt.Color inputTextColor = new java.awt.Color(43, 43, 43);
        java.awt.Color inputBg = Color.WHITE;
        java.awt.Color disabledBg = new java.awt.Color(220, 220, 220);
        Color inputDisabledBg = new Color(200, 230, 200);

        for (JTextField tf : polja) {
            tf.setFont(textFont);
            tf.setBorder(BorderFactory.createLineBorder(new java.awt.Color(46, 78, 31), 2));
            
         
             
            
        }

        // ComboBox
        jComboBoxStepenStrSpreme.setFont(comboFont);
        if(jComboBoxStepenStrSpreme.isEnabled()) {
            jComboBoxStepenStrSpreme.setBackground(Color.WHITE);
            jComboBoxStepenStrSpreme.setForeground(inputTextColor);
        } else {
            jComboBoxStepenStrSpreme.setBackground(disabledBg);
            jComboBoxStepenStrSpreme.setForeground(Color.DARK_GRAY);
        }

        // Dugmad
        JButton[] buttons = {
            jButtonDodaj, jButtonDodajStrSpremu, jButtonKreiraj, jButtonObrisi,
            jButtonOdustani, jButtonOdustaniStrSprema, jButtonPROMENIDUGME,
            jButtonPrikazi, jButtonSacuvajIzmene, jButtonSacuvajPromeneStrSprema, jButtonOdustani1
        };
        java.awt.Color dugmeEnabledBg = new java.awt.Color(46, 78, 31);
        java.awt.Color dugmeDisabledBg = new java.awt.Color(180, 180, 180);
        java.awt.Color dugmeEnabledFg = Color.WHITE;
        java.awt.Color dugmeDisabledFg = new java.awt.Color(80, 80, 80);

        for (JButton btn : buttons) {
            btn.setFont(dugmeFont);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);

            if(btn.isEnabled()) {
                btn.setBackground(dugmeEnabledBg);
                btn.setForeground(dugmeEnabledFg);
            } else {
                btn.setBackground(dugmeDisabledBg);
                btn.setForeground(dugmeDisabledFg);
            }
        }

        // Tabela (ako želiš da i ona dobije stil)
        jTableStrSprema.setFont(textFont);
        jTableStrSprema.setBackground(Color.WHITE);
        jTableStrSprema.setForeground(inputTextColor);
        jTableStrSprema.getTableHeader().setFont(labelFont);
    }

    
    

}
