/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Knjiga;
import model.Kupac;
import model.Prodavac;

/**
 *
 * @author Ljilja
 */
public class KreirajRacunForma extends javax.swing.JFrame {

    /**
     * Creates new form KreirajRacunForma
     */
    public KreirajRacunForma() {
         initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiraj racun");
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxKnjiga = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDostupnaKolicina = new javax.swing.JTextField();
        jButtonDodajKnjigu = new javax.swing.JButton();
        jButtonSacuvajPromeneKnjiga = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldKolicina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIznosRacuna = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxKupac = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxProdavac = new javax.swing.JComboBox<>();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonOdustaniRacun = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jButtonPromeniRacunDugme = new javax.swing.JButton();
        jButtonPrikaziStavku = new javax.swing.JButton();
        jButtonPromeni = new javax.swing.JButton();
        jButtonOdustani1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 243, 224));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavke);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, 659, 201));

        jLabel1.setText("Knjiga");

        jLabel3.setText("Naslov:");

        jLabel4.setText("Kolicina:");

        jTextFieldDostupnaKolicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDostupnaKolicinaActionPerformed(evt);
            }
        });

        jButtonDodajKnjigu.setText("Dodaj");

        jButtonSacuvajPromeneKnjiga.setText("Sacuvaj promene");

        jLabel10.setText("Dostupna kolicina: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxKnjiga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButtonDodajKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDostupnaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonSacuvajPromeneKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)))))))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDostupnaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDodajKnjigu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSacuvajPromeneKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 480, 210));

        jLabel5.setText("Iznos racuna:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 20));
        getContentPane().add(jTextFieldIznosRacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 180, -1));

        jLabel6.setText("Datum:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 46, 37, -1));

        jLabel8.setText("Kupac:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, -1));

        getContentPane().add(jComboBoxKupac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 270, -1));

        jLabel9.setText("Prodavac:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, -1));

        getContentPane().add(jComboBoxProdavac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 270, -1));

        jButtonKreiraj.setText("Kreiraj");
        getContentPane().add(jButtonKreiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 150, 30));

        jButtonOdustaniRacun.setText("Odustani");
        getContentPane().add(jButtonOdustaniRacun, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 150, 30));

        jLabelId.setText("Id racuna:");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, -1));
        getContentPane().add(jTextFieldDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 270, -1));

        jButtonPromeniRacunDugme.setText("Sacuvaj promene");
        getContentPane().add(jButtonPromeniRacunDugme, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 190, 30));

        jButtonPrikaziStavku.setText("Prikazi stavku");
        getContentPane().add(jButtonPrikaziStavku, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 150, 30));

        jButtonPromeni.setText("Promeni racun");
        getContentPane().add(jButtonPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 190, 30));

        jButtonOdustani1.setText("Odustani");
        getContentPane().add(jButtonOdustani1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDostupnaKolicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDostupnaKolicinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDostupnaKolicinaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajKnjigu;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonOdustani1;
    private javax.swing.JButton jButtonOdustaniRacun;
    private javax.swing.JButton jButtonPrikaziStavku;
    private javax.swing.JButton jButtonPromeni;
    private javax.swing.JButton jButtonPromeniRacunDugme;
    private javax.swing.JButton jButtonSacuvajPromeneKnjiga;
    private javax.swing.JComboBox<Knjiga> jComboBoxKnjiga;
    private javax.swing.JComboBox<Kupac> jComboBoxKupac;
    private javax.swing.JComboBox<Prodavac> jComboBoxProdavac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavke;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldDostupnaKolicina;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIznosRacuna;
    private javax.swing.JTextField jTextFieldKolicina;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonDodajKnjigu() {
        return jButtonDodajKnjigu;
    }

    public JButton getjButtonKreiraj() {
        return jButtonKreiraj;
    }

    public JButton getjButtonPrikaziStavku() {
        return jButtonPrikaziStavku;
    }

    public JButton getjButtonSacuvajPromeneKnjiga() {
        return jButtonSacuvajPromeneKnjiga;
    }


    public JButton getjButtonOdustaniRacun() {
        return jButtonOdustaniRacun;
    }

    public JComboBox<Knjiga> getjComboBoxKnjiga() {
        return jComboBoxKnjiga;
    }

    public JComboBox<Kupac> getjComboBoxKupac() {
        return jComboBoxKupac;
    }

    public JComboBox<Prodavac> getjComboBoxProdavac() {
        return jComboBoxProdavac;
    }

    public JTable getjTableStavke() {
        return jTableStavke;
    }

    public JTextField getjTextFieldDatum() {
        return jTextFieldDatum;
    }

    public JTextField getjTextFieldIznosRacuna() {
        return jTextFieldIznosRacuna;
    }

    public JTextField getjTextFieldKolicina() {
        return jTextFieldKolicina;
    }

    public JButton getjButtonPromeniRacunDugme() {
        return jButtonPromeniRacunDugme;
    }

    public JLabel getjLabelId() {
        return jLabelId;
    }

    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    public JButton getjButtonPromeni() {
        return jButtonPromeni;
    }

    public JButton getjButtonOdustani1() {
        return jButtonOdustani1;
    }

    public JTextField getjTextFieldDostupnaKolicina() {
        return jTextFieldDostupnaKolicina;
    }
    
    public void knjigaComboBoxAddActionListener(ActionListener actionListener){
            jComboBoxKnjiga.addActionListener(actionListener);
    }
    
    public void odustani1RacunAddActionListener(ActionListener actionListener){
        jButtonOdustani1.addActionListener(actionListener);
    }    


    public void promeniDugmeStavkuAddActionListener(ActionListener actionListener){
        jButtonPromeni.addActionListener(actionListener);
    }    

    public void prikaziStavkuAddActionListener(ActionListener actionListener){
        jButtonPrikaziStavku.addActionListener(actionListener);
    }

    public void sacuvajPromenuStavkeRacunAddActionListener(ActionListener actionListener){
        jButtonSacuvajPromeneKnjiga.addActionListener(actionListener);
    } 

    public void kreirajRacunAddActionListener(ActionListener actionListener){
        jButtonKreiraj.addActionListener(actionListener);
    }

    public void odustaniRacunAddActionListener(ActionListener actionListener){
        jButtonOdustaniRacun.addActionListener(actionListener);
    }


    public void dodajKnjiguAddActionListener(ActionListener actionListener){
        jButtonDodajKnjigu.addActionListener(actionListener);
    }

    public void promeniRacunAddActionListener(ActionListener actionListener){
        jButtonPromeniRacunDugme.addActionListener(actionListener);
    }
    
    private void dizajn() {
    // Fontovi
        Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
        Font textFont = new Font("Times New Roman", Font.BOLD, 18);
        Font dugmeFont = new Font("Times New Roman", Font.BOLD, 18);
        Font comboFont = new Font("Times New Roman", Font.PLAIN, 16);

        // Pozadina forme
        getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // svetlo siva
        setSize(1050, 500);
        setResizable(false);
        setLocationRelativeTo(null);

        // Pozadina panela
        jPanel1.setBackground(new java.awt.Color(220, 210, 200)); 
        jPanel1.setSize(300, 250);// toplija nijansa

        // Labele
        JLabel[] labele = {
            jLabel1, jLabel2, jLabel3, jLabel4, jLabel5,
            jLabel6, jLabel7, jLabel8, jLabel9, jLabelId
        };
        java.awt.Color labelColor = new java.awt.Color(46, 78, 31); // tamna zelena
        for (JLabel lbl : labele) {
            lbl.setFont(labelFont);
            lbl.setForeground(labelColor);
        }

        // Tekstualna polja
        JTextField[] polja = {
            jTextFieldDatum, jTextFieldId, jTextFieldIznosRacuna, jTextFieldDostupnaKolicina
        };
        java.awt.Color inputTextColor = new java.awt.Color(43, 43, 43);
        java.awt.Color inputBg = Color.WHITE;
        java.awt.Color disabledBg = new java.awt.Color(220, 220, 220);
        Color inputDisabledBg = new Color(200, 230, 200);

        for (JTextField tf : polja) {
            tf.setFont(textFont);
            tf.setBorder(BorderFactory.createLineBorder(new java.awt.Color(46, 78, 31), 2));
          
        }

        // ComboBox
        JComboBox<?>[] combos = { jComboBoxKnjiga, jComboBoxKupac, jComboBoxProdavac };
        for (JComboBox<?> combo : combos) {
            combo.setFont(comboFont);
            if(combo.isEnabled()) {
                combo.setBackground(Color.WHITE);
                combo.setForeground(inputTextColor);
            } else {
                combo.setBackground(disabledBg);
                combo.setForeground(Color.DARK_GRAY);
            }
        }

        // Dugmad
        JButton[] buttons = {
            jButtonDodajKnjigu, jButtonKreiraj, jButtonOdustani1, jButtonOdustaniRacun,
            jButtonPrikaziStavku, jButtonPromeni, jButtonPromeniRacunDugme,
            jButtonSacuvajPromeneKnjiga
        };
        java.awt.Color dugmeEnabledBg = new java.awt.Color(46, 78, 31);
        java.awt.Color dugmeDisabledBg = new java.awt.Color(180, 180, 180);
        java.awt.Color dugmeEnabledFg = Color.WHITE;
        java.awt.Color dugmeDisabledFg = new java.awt.Color(80, 80, 80);

        for (JButton btn : buttons) {
            btn.setFont(dugmeFont);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);

            if(btn.isEnabled()) {
                btn.setBackground(dugmeEnabledBg);
                btn.setForeground(dugmeEnabledFg);
            } else {
                btn.setBackground(dugmeDisabledBg);
                btn.setForeground(dugmeDisabledFg);
            }
        }

        // Tabela
        jTableStavke.setFont(textFont);
        jTableStavke.setBackground(Color.WHITE);
        jTableStavke.setForeground(inputTextColor);
        jTableStavke.getTableHeader().setFont(labelFont);
    }




}
