/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Mesto;

/**
 *
 * @author Ljilja
 */
public class KreirajMestoForma extends javax.swing.JFrame {

    private Mesto mesto;

    public Mesto getMesto() {
        return mesto;
    }

    public void setMesto(Mesto mesto) {
        this.mesto = mesto;
    }
    
  
    public KreirajMestoForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiraj mesto");
        dizajn();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonPromeniMesto = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonObrisi = new javax.swing.JButton();
        jButtonPromeniDugme = new javax.swing.JButton();
        jButtonOdustani1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 217, 183));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(125, 64, 71));
        jLabel1.setText("Naziv:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, -1));

        jButtonPromeniMesto.setText("Sacuvaj promene");
        getContentPane().add(jButtonPromeniMesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, 40));

        jButtonKreiraj.setText("Kreiraj");
        getContentPane().add(jButtonKreiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 140, 40));

        jButtonOdustani.setText("Odustani");
        getContentPane().add(jButtonOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, 40));
        getContentPane().add(jTextFieldNaziv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 220, 30));

        jLabelId.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(125, 64, 71));
        jLabelId.setText("Id:");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, -1));
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 50, 30));

        jButtonObrisi.setText("Obrisi");
        getContentPane().add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 140, 40));

        jButtonPromeniDugme.setText("Promeni");
        getContentPane().add(jButtonPromeniDugme, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, 40));

        jButtonOdustani1.setText("Odustani");
        getContentPane().add(jButtonOdustani1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonOdustani1;
    private javax.swing.JButton jButtonPromeniDugme;
    private javax.swing.JButton jButtonPromeniMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    public void kreirajMestoAddActionListener(ActionListener actionListener){
        jButtonKreiraj.addActionListener(actionListener);
    }

    public void promeniMestoAddActionListener(ActionListener actionListener){
        jButtonPromeniMesto.addActionListener(actionListener);
    }

    public void odustaniAddActionListener(ActionListener actionListener){
        jButtonOdustani.addActionListener(actionListener);
    }

    public void obrisiAddActionListener(ActionListener actionListener){
        jButtonObrisi.addActionListener(actionListener);

    }

    public void promeniDugmeAddActionListener(ActionListener actionListener){
        jButtonPromeniDugme.addActionListener(actionListener);

    }

    public void odustani1AddActionListener(ActionListener actionListener){
        jButtonOdustani1.addActionListener(actionListener);
    }

    public JButton getjButtonOdustani1() {
        return jButtonOdustani1;
    }   

    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }

    public JButton getjButtonPromeniDugme() {
        return jButtonPromeniDugme;
    }


    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    public JLabel getjLabelId() {
        return jLabelId;
    }

    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    public JButton getjButtonKreiraj() {
        return jButtonKreiraj;
    }

    public JButton getjButtonPromeniMesto() {
        return jButtonPromeniMesto;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

         
   private void dizajn() {
    // Fontovi
    Font labelFont = new Font("Times New Roman", Font.BOLD, 24);
    Font textFont = new Font("Times New Roman", Font.BOLD, 24);
    Font dugmeFont = new Font("Times New Roman", Font.BOLD, 24);

    // Pozadina forme
    getContentPane().setBackground(new java.awt.Color(0xDFF0D8)); // svetlo zelena pozadina
    setSize(500, 300);
    setResizable(false);
    this.setLocationRelativeTo(null);

    // Labele
    JLabel[] labele = { jLabel1, jLabel2, jLabelId };
    java.awt.Color labelColor = new java.awt.Color(0x2E4E1F); // tamno zelena
    for (JLabel lbl : labele) {
        lbl.setFont(labelFont);
        lbl.setForeground(labelColor);
    }

    // Tekstualna polja
    JTextField[] polja = { jTextFieldId, jTextFieldNaziv };
    java.awt.Color inputTextColor = new java.awt.Color(43, 43, 43); // tamno siva
    java.awt.Color inputBg = Color.WHITE;
    java.awt.Color disabledBg = new java.awt.Color(200, 230, 200); // svetlija zelena za disabled

    for (JTextField tf : polja) {
        tf.setFont(textFont);
        tf.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0x2E4E1F), 2));

        if(tf.isEnabled()) {
            tf.setBackground(inputBg);
            tf.setForeground(inputTextColor);
        } else {
            tf.setBackground(disabledBg);
            tf.setForeground(Color.DARK_GRAY);
        }
    }

    // Dugmad
    JButton[] buttons = { jButtonKreiraj, jButtonObrisi, jButtonOdustani, jButtonOdustani1, jButtonPromeniDugme, jButtonPromeniMesto };
    java.awt.Color dugmeEnabledBg = new java.awt.Color(0x2E4E1F); // tamno zelena
    java.awt.Color dugmeDisabledBg = new java.awt.Color(0xA3C293); // svetlija zelena za disabled
    java.awt.Color dugmeEnabledFg = Color.WHITE;
    java.awt.Color dugmeDisabledFg = new java.awt.Color(80, 80, 80); // tamno siva

    for (JButton btn : buttons) {
        btn.setFont(dugmeFont);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);

        if(btn.isEnabled()) {
            btn.setBackground(dugmeEnabledBg);
            btn.setForeground(dugmeEnabledFg);
        } else {
            btn.setBackground(dugmeDisabledBg);
            btn.setForeground(dugmeDisabledFg);
        }
    }
}
       
    


}
