/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ljilja
 */
public class PretraziStrSpremaForma extends javax.swing.JFrame {

    /**
     * Creates new form PretraziStrSprema
     */
    public PretraziStrSpremaForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretrazi strucnu spremu");
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonPrikaziSve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonPrikaziStrucnuSpremu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldStepen = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 243, 224));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonPrikaziSve.setText("Prikazi sve");

        jLabel1.setText("Prikazi sve strucne spreme:");

        jButtonPrikaziStrucnuSpremu.setText("Prikazi strucnu spremu");

        jLabel2.setText("Filtriraj prema nazivu:");

        jButtonPretrazi.setText("Pretrazi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldStepen, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPrikaziSve, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPrikaziStrucnuSpremu)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonPrikaziSve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldStepen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPrikaziStrucnuSpremu)
                        .addGap(65, 65, 65))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikaziStrucnuSpremu;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldStepen;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonPrikaziSve() {
        return jButtonPrikaziSve;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    public JButton getjButtonPrikaziStrucnuSpremu() {
        return jButtonPrikaziStrucnuSpremu;
    }

    public JTextField getjTextFieldStepen() {
        return jTextFieldStepen;
    }

    public void prikaziAddActionListener(ActionListener actionListener){
        jButtonPrikaziStrucnuSpremu.addActionListener(actionListener);
    }
    
    public void vratiListuSviStrSpremaAddActionListener(ActionListener actionListener){
        jButtonPrikaziSve.addActionListener(actionListener);
    }
    
    public void vratiListuStrSpremaAddActionListener(ActionListener actionListener){
        jButtonPretrazi.addActionListener(actionListener);
    }
    
    private void dizajn() {
    // Fontovi
        Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
        Font textFont = new Font("Times New Roman", Font.PLAIN, 16);
        Font dugmeFont = new Font("Times New Roman", Font.BOLD, 16);

        // Pozadina forme
        getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // svetlo siva
        setSize(700, 400);
        setResizable(false);
        setLocationRelativeTo(null);

        // Labele
        JLabel[] labele = { jLabel1, jLabel2 };
        java.awt.Color labelColor = new java.awt.Color(46, 78, 31); // tamno zelena
        for (JLabel lbl : labele) {
            lbl.setFont(labelFont);
            lbl.setForeground(labelColor);
        }

        // Tekstualno polje
        java.awt.Color inputTextColor = new java.awt.Color(43, 43, 43); // tamno siva
        java.awt.Color inputBg = Color.WHITE;
        java.awt.Color disabledBg = new java.awt.Color(220, 220, 220); // svetlije siva kada disabled

        jTextFieldStepen.setFont(textFont);
        jTextFieldStepen.setBorder(BorderFactory.createLineBorder(new java.awt.Color(46, 78, 31), 2));
        if(jTextFieldStepen.isEnabled()) {
            jTextFieldStepen.setBackground(inputBg);
            jTextFieldStepen.setForeground(inputTextColor);
        } else {
            jTextFieldStepen.setBackground(disabledBg);
            jTextFieldStepen.setForeground(Color.DARK_GRAY);
        }

        // Dugmad
        JButton[] buttons = { jButtonPretrazi, jButtonPrikaziStrucnuSpremu, jButtonPrikaziSve };
        java.awt.Color dugmeEnabledBg = new java.awt.Color(46, 78, 31); // tamno zelena
        java.awt.Color dugmeDisabledBg = new java.awt.Color(180, 180, 180); // siva
        java.awt.Color dugmeEnabledFg = Color.WHITE;
        java.awt.Color dugmeDisabledFg = new java.awt.Color(80, 80, 80); // tamno siva

        for (JButton btn : buttons) {
            btn.setFont(dugmeFont);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);
            if(btn.isEnabled()) {
                btn.setBackground(dugmeEnabledBg);
                btn.setForeground(dugmeEnabledFg);
            } else {
                btn.setBackground(dugmeDisabledBg);
                btn.setForeground(dugmeDisabledFg);
            }
        }

        // Tabela
        jTable1.setFont(textFont);
        jTable1.setBackground(Color.WHITE);
        jTable1.setForeground(inputTextColor);
        jTable1.getTableHeader().setFont(labelFont);
}

    
    
    
    
    
    

 }
