/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Mesto;

/**
 *
 * @author Ljilja
 */
public class PretraziKupcaForma extends javax.swing.JFrame {

    /**
     * Creates new form PretraziKupcaForma
     */
    public PretraziKupcaForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretrazi kupca");
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKupac = new javax.swing.JTable();
        jButtonPrikaziSveKupce = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonPrikaziKupca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldImeIPrezime = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jComboBoxMesto = new javax.swing.JComboBox<>();
        jCheckBoxImeIPrezime = new javax.swing.JCheckBox();
        jCheckBoxMesto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 243, 224));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableKupac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKupac);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 660, 193));

        jButtonPrikaziSveKupce.setText("Prikazi sve ");
        getContentPane().add(jButtonPrikaziSveKupce, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 177, -1));

        jLabel1.setText("Prikazi sve kupce:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 30, 190, -1));

        jButtonPrikaziKupca.setText("Prikazi kupca");
        getContentPane().add(jButtonPrikaziKupca, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 180, -1));

        jLabel2.setText("Filter prema imenu i prezimenu:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 290, -1));

        jLabel3.setText("Filter prema mestu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 230, -1));
        getContentPane().add(jTextFieldImeIPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 230, -1));

        jButtonPretrazi.setText("Pretrazi");
        getContentPane().add(jButtonPretrazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 109, -1));

        jComboBoxMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMestoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 240, -1));
        getContentPane().add(jCheckBoxImeIPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(jCheckBoxMesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMestoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikaziKupca;
    private javax.swing.JButton jButtonPrikaziSveKupce;
    private javax.swing.JCheckBox jCheckBoxImeIPrezime;
    private javax.swing.JCheckBox jCheckBoxMesto;
    private javax.swing.JComboBox<Mesto> jComboBoxMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKupac;
    private javax.swing.JTextField jTextFieldImeIPrezime;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonPrikaziSveKupce() {
        return jButtonPrikaziSveKupce;
    }

    public JTable getjTableKupac() {
        return jTableKupac;
    }

    public JButton getjButtonPrikaziKupca() {
        return jButtonPrikaziKupca;
    }

    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    public JTextField getjTextFieldImeIPrezime() {
        return jTextFieldImeIPrezime;
    }

    public JComboBox<Mesto> getjComboBoxMesto() {
        return jComboBoxMesto;
    }

    public JCheckBox getjCheckBoxImeIPrezime() {
        return jCheckBoxImeIPrezime;
    }

    public JCheckBox getjCheckBoxMesto() {
        return jCheckBoxMesto;
    }


    public void vratiListuSvihKupacaAddActionListener(ActionListener actionListener){
        jButtonPrikaziSveKupce.addActionListener(actionListener);
    }

    public void pretraziKupcaAddActionListener(ActionListener actionListener){
        jButtonPrikaziKupca.addActionListener(actionListener);
    }

    public void vratiListuSaUslovomKupcaAddActionListener(ActionListener actionListener){
        jButtonPretrazi.addActionListener(actionListener);
    }
    
    
    private void dizajn() {
        // Fontovi
        Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
        Font textFont = new Font("Times New Roman", Font.PLAIN, 16);
        Font dugmeFont = new Font("Times New Roman", Font.BOLD, 16);
        Font checkFont = new Font("Times New Roman", Font.PLAIN, 16);

        // Pozadina forme
        getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // svetlo siva
        setSize(800, 400);
        setResizable(false);
        setLocationRelativeTo(null);

        // Labele
        JLabel[] labele = { jLabel1, jLabel2, jLabel3 };
        java.awt.Color labelColor = new java.awt.Color(46, 78, 31); // tamna zelena
        for (JLabel lbl : labele) {
            lbl.setFont(labelFont);
            lbl.setForeground(labelColor);
        }

        // Tekstualna polja
        JTextField[] polja = { jTextFieldImeIPrezime };
        java.awt.Color inputTextColor = new java.awt.Color(43, 43, 43);
        java.awt.Color inputBg = Color.WHITE;
        java.awt.Color disabledBg = new java.awt.Color(220, 220, 220);

        for (JTextField tf : polja) {
            tf.setFont(textFont);
            tf.setBorder(BorderFactory.createLineBorder(new java.awt.Color(46, 78, 31), 2));
            if(tf.isEnabled()) {
                tf.setBackground(inputBg);
                tf.setForeground(inputTextColor);
            } else {
                tf.setBackground(disabledBg);
                tf.setForeground(Color.DARK_GRAY);
            }
        }

        // Dugmad
        JButton[] buttons = { jButtonPretrazi, jButtonPrikaziKupca, jButtonPrikaziSveKupce };
        java.awt.Color dugmeEnabledBg = new java.awt.Color(46, 78, 31);
        java.awt.Color dugmeDisabledBg = new java.awt.Color(180, 180, 180);
        java.awt.Color dugmeEnabledFg = Color.WHITE;
        java.awt.Color dugmeDisabledFg = new java.awt.Color(80, 80, 80);

        for (JButton btn : buttons) {
            btn.setFont(dugmeFont);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);

            if(btn.isEnabled()) {
                btn.setBackground(dugmeEnabledBg);
                btn.setForeground(dugmeEnabledFg);
            } else {
                btn.setBackground(dugmeDisabledBg);
                btn.setForeground(dugmeDisabledFg);
            }
        }

        // Checkboxovi
        JCheckBox[] checkovi = { jCheckBoxImeIPrezime, jCheckBoxMesto };
        for (JCheckBox cb : checkovi) {
            cb.setFont(checkFont);
            cb.setBackground(getContentPane().getBackground());
            cb.setForeground(labelColor);
        }

        // ComboBox
        jComboBoxMesto.setFont(textFont);
        jComboBoxMesto.setBackground(Color.WHITE);
        jComboBoxMesto.setForeground(inputTextColor);

        // Tabela
        jTableKupac.setFont(textFont);
        jTableKupac.setBackground(Color.WHITE);
        jTableKupac.setForeground(inputTextColor);
        jTableKupac.getTableHeader().setFont(labelFont);
    }

    
    
    


}
