/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Knjiga;
import model.Kupac;
import model.Prodavac;

/**
 *
 * @author Ljilja
 */
public class PretraziRacunForma extends javax.swing.JFrame {

    /**
     * Creates new form PretraziRacunForma
     */
    public PretraziRacunForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretrazi racun");
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRacun = new javax.swing.JTable();
        jButtonPrikaziRacun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonPrikaziSve = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxKnjiga = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxProdavac = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxKupac = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIznos = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jCheckBoxKnjiga = new javax.swing.JCheckBox();
        jCheckBoxProdavac = new javax.swing.JCheckBox();
        jCheckBoxKupac = new javax.swing.JCheckBox();
        jCheckBoxRacun = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 243, 224));

        jTableRacun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRacun);

        jButtonPrikaziRacun.setText("Prikazi racun");

        jLabel1.setText("Prikazi sve racune:");

        jButtonPrikaziSve.setText("Prikazi sve");

        jLabel2.setText("Filter prema knjizi:");

        jLabel3.setText("Filter prema prodavcu:");

        jLabel4.setText("Filter prema kupcu:");

        jLabel5.setText("FIlter prema iznosu racuna:");

        jButtonPretrazi.setText("Pretrazi");

        jCheckBoxKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxKnjigaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPrikaziSve, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jButtonPrikaziRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBoxRacun)
                                .addComponent(jCheckBoxProdavac)
                                .addComponent(jCheckBoxKnjiga)
                                .addComponent(jCheckBoxKupac))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxKupac, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jComboBoxProdavac, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(639, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrikaziRacun)
                    .addComponent(jButtonPrikaziSve)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxKnjiga)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBoxKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxProdavac)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jComboBoxProdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxKupac)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jComboBoxKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxRacun)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPretrazi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxKnjigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxKnjigaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikaziRacun;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JCheckBox jCheckBoxKnjiga;
    private javax.swing.JCheckBox jCheckBoxKupac;
    private javax.swing.JCheckBox jCheckBoxProdavac;
    private javax.swing.JCheckBox jCheckBoxRacun;
    private javax.swing.JComboBox<Knjiga> jComboBoxKnjiga;
    private javax.swing.JComboBox<Kupac> jComboBoxKupac;
    private javax.swing.JComboBox<Prodavac> jComboBoxProdavac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRacun;
    private javax.swing.JTextField jTextFieldIznos;
    // End of variables declaration//GEN-END:variables

    public void pretraziRacunAddActionListener(ActionListener actionListener){
        jButtonPrikaziRacun.addActionListener(actionListener);
    }
    public void vratiListuRacunSaUslovomAddActionListener(ActionListener actionListener){
        jButtonPretrazi.addActionListener(actionListener);
    }
    public void vratiListuSviRacunAddActionListener(ActionListener actionListener){
        jButtonPrikaziSve.addActionListener(actionListener);
    }

    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    public JButton getjButtonPrikaziRacun() {
        return jButtonPrikaziRacun;
    }

    public JButton getjButtonPrikaziSve() {
        return jButtonPrikaziSve;
    }

    public JComboBox<Knjiga> getjComboBoxKnjiga() {
        return jComboBoxKnjiga;
    }

    public JComboBox<Kupac> getjComboBoxKupac() {
        return jComboBoxKupac;
    }

    public JComboBox<Prodavac> getjComboBoxProdavac() {
        return jComboBoxProdavac;
    }

    public JTable getjTableRacun() {
        return jTableRacun;
    }

    public JTextField getjTextFieldIznos() {
        return jTextFieldIznos;
    }

    public JCheckBox getjCheckBoxKnjiga() {
        return jCheckBoxKnjiga;
    }

    public JCheckBox getjCheckBoxKupac() {
        return jCheckBoxKupac;
    }

    public JCheckBox getjCheckBoxProdavac() {
        return jCheckBoxProdavac;
    }

    public JCheckBox getjCheckBoxRacun() {
        return jCheckBoxRacun;
    }

    private void dizajn() {
        // Fontovi
        Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
        Font textFont = new Font("Times New Roman", Font.PLAIN, 16);
        Font dugmeFont = new Font("Times New Roman", Font.BOLD, 16);

        // Pozadina forme
        getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // svetlo siva
        setSize(780, 550);
        setResizable(false);
        setLocationRelativeTo(null);

        // Panel možeš dodati ako postoji
        // jPanel1.setBackground(new java.awt.Color(220, 200, 180));

        // Labele
        JLabel[] labels = {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5};
        for (JLabel lbl : labels) {
            lbl.setFont(labelFont);
            lbl.setForeground(new java.awt.Color(46, 78, 31)); // tamna zelena
        }

        // Dugmad
        JButton[] buttons = {jButtonPretrazi, jButtonPrikaziRacun, jButtonPrikaziSve};
        for (JButton btn : buttons) {
            btn.setFont(dugmeFont);
            btn.setBackground(new java.awt.Color(46, 78, 31)); // tamna zelena
            btn.setForeground(Color.WHITE);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);
        }

        // CheckBox-ovi
        JCheckBox[] checkBoxes = {jCheckBoxKnjiga, jCheckBoxKupac, jCheckBoxProdavac, jCheckBoxRacun};
        for (JCheckBox cb : checkBoxes) {
            cb.setFont(textFont);
            cb.setForeground(new java.awt.Color(46, 78, 31)); // tamna zelena
            cb.setBackground(new java.awt.Color(245, 245, 245)); // da se uklopi sa pozadinom forme
        }

        // ComboBox-ovi
        JComboBox[] combos = {jComboBoxKnjiga, jComboBoxKupac, jComboBoxProdavac};
        for (JComboBox cb : combos) {
            cb.setFont(textFont);
            cb.setBackground(Color.WHITE);
            cb.setForeground(new java.awt.Color(43, 43, 43)); // tamno siva
        }

        // Tekstualna polja
        JTextField[] textFields = {jTextFieldIznos};
        for (JTextField tf : textFields) {
            tf.setFont(textFont);
            tf.setForeground(new java.awt.Color(43, 43, 43)); // tamno siva
            tf.setBackground(Color.WHITE);
            tf.setBorder(BorderFactory.createLineBorder(new java.awt.Color(46, 78, 31), 2));
            if (!tf.isEditable()) {
                tf.setBackground(new java.awt.Color(230, 230, 230)); // svetlija boja za disabled
            }
        }

        // JTable
        jTableRacun.setFont(textFont);
        jTableRacun.setBackground(Color.WHITE);
        jTableRacun.setForeground(new java.awt.Color(43, 43, 43));
        jTableRacun.setRowHeight(25);
        jTableRacun.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 16));
}

    









}
