/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.tabele.ModelTabeleKnjige;

/**
 *
 * @author Ljilja
 */
public class PretraziKnjigeForma extends javax.swing.JFrame {

    /**
     * Creates new form PrikazKnjigaForma
     */
    public PretraziKnjigeForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretrazi knjigu");
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKnjige = new javax.swing.JTable();
        jButtonPrikaziSve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonPrikaziKnjigu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNaslov = new javax.swing.JTextField();
        jButtonVratiListuKnjiga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 243, 224));

        jTableKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKnjige);

        jButtonPrikaziSve.setText("Prikazi sve ");
        jButtonPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSveActionPerformed(evt);
            }
        });

        jLabel1.setText("Prikazite sve knjige");

        jButtonPrikaziKnjigu.setText("Prikazi knjigu");
        jButtonPrikaziKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziKnjiguActionPerformed(evt);
            }
        });

        jLabel2.setText("Filter prema naslovu:");

        jTextFieldNaslov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNaslovActionPerformed(evt);
            }
        });

        jButtonVratiListuKnjiga.setText("Pretrazi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrikaziSve, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrikaziKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVratiListuKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPrikaziSve)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonPrikaziKnjigu)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVratiListuKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrikaziKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziKnjiguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrikaziKnjiguActionPerformed

    private void jTextFieldNaslovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNaslovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNaslovActionPerformed

    private void jButtonPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrikaziSveActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrikaziKnjigu;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JButton jButtonVratiListuKnjiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKnjige;
    private javax.swing.JTextField jTextFieldNaslov;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableKnjige() {
        return jTableKnjige;
    }

    public JButton getjButtonPrikaziSve() {
        return jButtonPrikaziSve;
    }

    public JButton getjButtonPrikaziKnjigu() {
        return jButtonPrikaziKnjigu;
    }

    public void setjButtonPrikaziKnjigu(JButton jButtonPrikaziKnjigu) {
        this.jButtonPrikaziKnjigu = jButtonPrikaziKnjigu;
    }

    public JButton getjButtonVratiListuKnjiga() {
        return jButtonVratiListuKnjiga;
    }

    public void setjButtonVratiListuKnjiga(JButton jButtonVratiListuKnjiga) {
        this.jButtonVratiListuKnjiga = jButtonVratiListuKnjiga;
    }

    public JTextField getjTextFieldNaslov() {
        return jTextFieldNaslov;
    }

    public void setjTextFieldNaslov(JTextField jTextFieldNaslov) {
        this.jTextFieldNaslov = jTextFieldNaslov;
    }
    
    public void vratiListuKnjigaKnjigaAddActionListener(ActionListener actionListener){
        jButtonVratiListuKnjiga.addActionListener(actionListener);
    }

 
    public void vratiListuSvihKnjigaAddActionListener(ActionListener actionListener) {
        jButtonPrikaziSve.addActionListener(actionListener);
    }
     

    public void prikaziKnjiguAddActionListener(ActionListener actionListener) {
        jButtonPrikaziKnjigu.addActionListener(actionListener);
    } 
     
 
private void dizajn() {
    // Fontovi
    Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
    Font textFont = new Font("Times New Roman", Font.PLAIN, 18);
    Font dugmeFont = new Font("Times New Roman", Font.BOLD, 18);

    // Boje
    Color pozadinaForme = new Color(245, 245, 245); // svetlo siva
    Color labelColor = new Color(46, 78, 31);       // tamno zelena
    Color inputTextColor = new Color(43, 43, 43);   // tamno siva
    Color inputBg = Color.WHITE;
    Color inputDisabledBg = new Color(220, 220, 220);
    Color dugmeEnabledBg = new Color(46, 78, 31);
    Color dugmeEnabledFg = Color.WHITE;
    Color dugmeDisabledBg = new Color(180, 180, 180);
    Color dugmeDisabledFg = new Color(80, 80, 80);

    // Osnovna forma
    getContentPane().setBackground(pozadinaForme);
    setSize(770, 400);
    setResizable(false);
    setLocationRelativeTo(null);
    setLayout(null); // apsolutni layout

    // Labela
    jLabel2.setFont(labelFont);
    jLabel2.setForeground(labelColor);
    jLabel1.setFont(labelFont);
    jLabel1.setForeground(labelColor);

    // TextField
    jTextFieldNaslov.setFont(textFont);
   
    jTextFieldNaslov.setBorder(BorderFactory.createLineBorder(new Color(46, 78, 31), 2));
    if (jTextFieldNaslov.isEnabled()) {
        jTextFieldNaslov.setBackground(inputBg);
        jTextFieldNaslov.setForeground(inputTextColor);
    } else {
        jTextFieldNaslov.setBackground(inputDisabledBg);
        jTextFieldNaslov.setForeground(Color.DARK_GRAY);
    }

    // Dugmad
    JButton[] buttons = { jButtonPrikaziKnjigu, jButtonPrikaziSve, jButtonVratiListuKnjiga };
   
    for (JButton btn : buttons) {
        btn.setFont(dugmeFont);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
       

        if (btn.isEnabled()) {
            btn.setBackground(dugmeEnabledBg);
            btn.setForeground(dugmeEnabledFg);
        } else {
            btn.setBackground(dugmeDisabledBg);
            btn.setForeground(dugmeDisabledFg);
        }
    }

    // Tabela i JScrollPane
    jTableKnjige.setFont(textFont);
    jTableKnjige.setBackground(Color.WHITE);
    jTableKnjige.setForeground(inputTextColor);
    jTableKnjige.setRowHeight(22);
    jTableKnjige.getTableHeader().setFont(labelFont);

    
}

 
     
     
}
