/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import koordinator.Koordinator;
import model.StrSprema;

/**
 *
 * @author Ljilja
 */
public class PretraziProdavcaForma extends javax.swing.JFrame {

    /**
     * Creates new form PretraziProdavcaForma
     */
    public PretraziProdavcaForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretrazi prodavca");
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdavci = new javax.swing.JTable();
        jButtonPrikaziSve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonPrikaziProdavca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonPretrazi = new javax.swing.JButton();
        jComboBoxStrSprema = new javax.swing.JComboBox<>();
        jCheckBoxImeIPrezime = new javax.swing.JCheckBox();
        jCheckBoxStrSprema = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 243, 224));

        jTableProdavci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProdavci);

        jButtonPrikaziSve.setText("Prikazi sve");
        jButtonPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSveActionPerformed(evt);
            }
        });

        jLabel1.setText("Prikazi sve prodavce:");

        jButtonPrikaziProdavca.setText("Prikazi prodavca");
        jButtonPrikaziProdavca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziProdavcaActionPerformed(evt);
            }
        });

        jLabel2.setText("Filter prema imenu i prezimenu:");

        jLabel3.setText("Filter prema strucnoj spremi:");

        jButtonPretrazi.setText("Pretrazi");

        jCheckBoxImeIPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxImeIPrezimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxImeIPrezime)
                    .addComponent(jCheckBoxStrSprema, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPrikaziSve)
                        .addGap(215, 215, 215)
                        .addComponent(jButtonPrikaziProdavca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxStrSprema, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonPrikaziSve)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonPrikaziProdavca)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxImeIPrezime)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonPretrazi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxStrSprema, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBoxStrSprema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSveActionPerformed
        //Koordinator.getInstance().otvoriPretraziProdavcaFormu();
    }//GEN-LAST:event_jButtonPrikaziSveActionPerformed

    private void jButtonPrikaziProdavcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziProdavcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrikaziProdavcaActionPerformed

    private void jCheckBoxImeIPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxImeIPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxImeIPrezimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikaziProdavca;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JCheckBox jCheckBoxImeIPrezime;
    private javax.swing.JCheckBox jCheckBoxStrSprema;
    private javax.swing.JComboBox<StrSprema> jComboBoxStrSprema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdavci;
    private javax.swing.JTextField jTextFieldIme;
    // End of variables declaration//GEN-END:variables

    
    public void vratiListuProdavacAddActionListener(ActionListener actionListener){
        jButtonPretrazi.addActionListener(actionListener);
    }
    public void prikaziProdavacAddActionListener(ActionListener actionListener){
        jButtonPrikaziProdavca.addActionListener(actionListener);
    }
    
    public void vratiListuSvihProdavacaAddActionListener(ActionListener actionListener){
        jButtonPrikaziSve.addActionListener(actionListener);
    }


    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    public JButton getjButtonPrikaziProdavca() {
        return jButtonPrikaziProdavca;
    }

    public JButton getjButtonPrikaziSve() {
        return jButtonPrikaziSve;
    }

    public JTable getjTableProdavci() {
        return jTableProdavci;
    }

    public JTextField getjTextFieldIme() {
        return jTextFieldIme;
    }

    public JComboBox<StrSprema> getjComboBoxStrSprema() {
        return jComboBoxStrSprema;
    }

    public JCheckBox getjCheckBoxImeIPrezime() {
        return jCheckBoxImeIPrezime;
    }

    public JCheckBox getjCheckBoxStrSprema() {
        return jCheckBoxStrSprema;
    }

    private void dizajn() {
    // Fontovi
        Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
        Font textFont = new Font("Times New Roman", Font.PLAIN, 16);
        Font dugmeFont = new Font("Times New Roman", Font.BOLD, 16);

        // Pozadina forme
        getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // svetlo siva
        setSize(850, 450);
        setResizable(false);
        setLocationRelativeTo(null);

        // Labele
        JLabel[] labele = { jLabel1, jLabel2, jLabel3 };
        java.awt.Color labelColor = new java.awt.Color(46, 78, 31); // tamno zelena
        for (JLabel lbl : labele) {
            lbl.setFont(labelFont);
            lbl.setForeground(labelColor);
        }

        // Tekstualno polje
        java.awt.Color inputTextColor = new java.awt.Color(43, 43, 43);
        java.awt.Color inputBg = Color.WHITE;
        java.awt.Color disabledBg = new java.awt.Color(220, 220, 220);

        jTextFieldIme.setFont(textFont);
        jTextFieldIme.setBorder(BorderFactory.createLineBorder(new java.awt.Color(46, 78, 31), 2));
        if(jTextFieldIme.isEnabled()) {
            jTextFieldIme.setBackground(inputBg);
            jTextFieldIme.setForeground(inputTextColor);
        } else {
            jTextFieldIme.setBackground(disabledBg);
            jTextFieldIme.setForeground(Color.DARK_GRAY);
        }

        // ComboBox
        jComboBoxStrSprema.setFont(textFont);
        if(jComboBoxStrSprema.isEnabled()) {
            jComboBoxStrSprema.setBackground(inputBg);
            jComboBoxStrSprema.setForeground(inputTextColor);
        } else {
            jComboBoxStrSprema.setBackground(disabledBg);
            jComboBoxStrSprema.setForeground(Color.DARK_GRAY);
        }

        // CheckBox-ovi
        JCheckBox[] checkBoxes = { jCheckBoxImeIPrezime, jCheckBoxStrSprema };
        for(JCheckBox cb : checkBoxes){
            cb.setFont(textFont);
            cb.setForeground(new java.awt.Color(46,78,31));
            cb.setBackground(new java.awt.Color(245,245,245));
        }

        // Dugmad
        JButton[] buttons = { jButtonPretrazi, jButtonPrikaziProdavca, jButtonPrikaziSve };
        java.awt.Color dugmeEnabledBg = new java.awt.Color(46, 78, 31);
        java.awt.Color dugmeDisabledBg = new java.awt.Color(180, 180, 180);
        java.awt.Color dugmeEnabledFg = Color.WHITE;
        java.awt.Color dugmeDisabledFg = new java.awt.Color(80, 80, 80);

        for (JButton btn : buttons) {
            btn.setFont(dugmeFont);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);

            if(btn.isEnabled()) {
                btn.setBackground(dugmeEnabledBg);
                btn.setForeground(dugmeEnabledFg);
            } else {
                btn.setBackground(dugmeDisabledBg);
                btn.setForeground(dugmeDisabledFg);
            }
        }

        // Tabela
        jTableProdavci.setFont(textFont);
        jTableProdavci.setBackground(Color.WHITE);
        jTableProdavci.setForeground(inputTextColor);
        jTableProdavci.getTableHeader().setFont(labelFont);
}

    
  
    
    

}
