/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ljilja
 */
public class PrijaviProdavcaForma extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PrijaviProdavcaForma() {
        setTitle("Prijava prodavca");
        initComponents();
       
        dizajn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKorisnickoIme = new javax.swing.JTextField();
        jButtonPrijaviSe = new javax.swing.JButton();
        jPasswordFieldSifra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 243, 224));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(125, 64, 71));
        jLabel1.setText("Korisnicko ime:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(125, 64, 71));
        jLabel2.setText("Sifra:");

        jButtonPrijaviSe.setText("Prijavite se");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldSifra))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrijaviSe)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButtonPrijaviSe)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonPrijaviSe() {
        return jButtonPrijaviSe;
    }

    public void setjButtonPrijaviSe(JButton jButtonPrijaviSe) {
        this.jButtonPrijaviSe = jButtonPrijaviSe;
    }

    public JTextField getjTextFieldKorisnickoIme() {
        return jTextFieldKorisnickoIme;
    }

    public void setjTextFieldKorisnickoIme(JTextField jTextFieldKorisnickoIme) {
        this.jTextFieldKorisnickoIme = jTextFieldKorisnickoIme;
    }

    public JPasswordField getjPasswordFieldSifra() {
        return jPasswordFieldSifra;
    }

    public void setjPasswordFieldSifra(JPasswordField jPasswordFieldSifra) {
        this.jPasswordFieldSifra = jPasswordFieldSifra;
    }

    
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrijaviSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordFieldSifra;
    private javax.swing.JTextField jTextFieldKorisnickoIme;
    // End of variables declaration//GEN-END:variables

   

    public void prijavaProdavcaAddActionListener(ActionListener actionListener) {
        jButtonPrijaviSe.addActionListener(actionListener);
    }

  public void dizajn() {
      

    getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // svetlo siva #F5F5F5
    setSize(500, 300);
    setResizable(false);
    this.setLocationRelativeTo(null);

    
    jButtonPrijaviSe.setBackground(new java.awt.Color(46, 78, 31)); // tamno zelena #2E4E1F
    jButtonPrijaviSe.setForeground(Color.WHITE);
    jButtonPrijaviSe.setFont(new Font("Times New Roman", Font.BOLD, 18));

    
    java.awt.Color labelColor = new java.awt.Color(46, 78, 31); // tamno zelena
    Font labelFont = new Font("Times New Roman", Font.BOLD, 18);
    jLabel1.setForeground(labelColor);
    jLabel1.setFont(labelFont);
    jLabel2.setForeground(labelColor);
    jLabel2.setFont(labelFont);

    
    java.awt.Color inputTextColor = new java.awt.Color(43, 43, 43); // tamno siva #2B2B2B
    java.awt.Color inputBgColor = Color.WHITE;
    Font inputFont = new Font("Times New Roman", Font.PLAIN, 18);

    jTextFieldKorisnickoIme.setForeground(inputTextColor);
    jTextFieldKorisnickoIme.setBackground(inputBgColor);
    jTextFieldKorisnickoIme.setFont(inputFont);

    jPasswordFieldSifra.setForeground(inputTextColor);
    jPasswordFieldSifra.setBackground(inputBgColor);
    jPasswordFieldSifra.setFont(inputFont);
}

}
