package forme;

import kontroler.Kontroler;
import db.repozitorijum.DBKonekcija;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Prodavac;
import model.tabele.ModelTabeleProdavac;
import niti.ObradaKlijentskihZahteva;
import niti.ServerskaNit;

/**
 *
 * @author Andjela
 */
public class ServerskaForma extends javax.swing.JFrame {
    
    ServerskaNit ps;
    FormaKonfiguracija fk;
    private List<Prodavac> sviKorisnici = new ArrayList<>();
    private List<Prodavac> nepovezaniKorisnici = new ArrayList<>();
    
    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        setTitle("Pokreni server");
       
         dizajn();
        jLabelStatus.setText("SERVER NIJE POKRENUT");
        jButtonZaustaviServer.setEnabled(false);
        
        jTableNepovezaniKorisnici.setModel(new ModelTabeleProdavac(new ArrayList<>()));
        jTablePovezaniKorisnici.setModel(new ModelTabeleProdavac(new ArrayList<>()));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jButtonPokreniServer = new javax.swing.JButton();
        jButtonZaustaviServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePovezaniKorisnici = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNepovezaniKorisnici = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 217, 183));
        setForeground(new java.awt.Color(238, 217, 183));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPokreniServer.setText("POKRENI SERVER");
        jButtonPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPokreniServerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPokreniServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 180, 30));

        jButtonZaustaviServer.setText("ZAUSTAVI SERVER");
        jButtonZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZaustaviServerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonZaustaviServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 180, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 46, 46));
        jLabel1.setText("Status:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 72, -1));

        jLabelStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(46, 46, 46));
        jLabelStatus.setText("jLabel2");
        getContentPane().add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 280, 20));

        jTablePovezaniKorisnici.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jTablePovezaniKorisnici.setForeground(new java.awt.Color(5, 5, 5));
        jTablePovezaniKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePovezaniKorisnici);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 640, 204));

        jTableNepovezaniKorisnici.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jTableNepovezaniKorisnici.setForeground(new java.awt.Color(5, 5, 5));
        jTableNepovezaniKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableNepovezaniKorisnici);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 650, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 46, 46));
        jLabel2.setText("Povezani korisnici:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 241, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 46, 46));
        jLabel3.setText("Nepovezani korisnici:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, -1));

        jMenu1.setForeground(new java.awt.Color(46, 46, 46));
        jMenu1.setText("Konfiguracija");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(46, 46, 46));
        jMenuItem4.setText("kreiraj konfiguraciju");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokreniServerActionPerformed
      
        ps = new ServerskaNit();
       
        
       ps.start();
       
       jLabelStatus.setText("SERVER JE POKRENUT");
      
       jButtonZaustaviServer.setEnabled(true);
       jButtonPokreniServer.setEnabled(false);
       
        
       Kontroler.getInstance().setSf(this);
       
       
        
 
        try {
            sviKorisnici = Kontroler.getInstance().vratiListuSvihProdavaca();
        } catch (Exception ex) {
            System.err.println("Sistem ne može da učita prodavce iz baze.");
        }
        if (sviKorisnici == null) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita prodavce iz baze. Proverite da li je uspostavljena veza sa MySQL serverom.", "Greška", JOptionPane.ERROR_MESSAGE);
            ps.zaustaviServer();
            return;
        }

     
        nepovezaniKorisnici = new ArrayList<>();
        List<Prodavac> povezaniKorisnici = new ArrayList<>();
        for (ObradaKlijentskihZahteva prodavac : ServerskaNit.getPrijavljeniKorisnici()) {
            Prodavac p = new Prodavac(prodavac.getIme(),prodavac.getPrezime(),prodavac.getKorisnickoIme(),prodavac.getSifra(),prodavac.getEmail());
            povezaniKorisnici.add(p);
        }
        for (Prodavac p : sviKorisnici) {
            if (!povezaniKorisnici.contains(p)) {
                nepovezaniKorisnici.add(p);
            }
        }

        ModelTabeleProdavac mtp1 = (ModelTabeleProdavac) jTableNepovezaniKorisnici.getModel();
        mtp1.setProdavci(nepovezaniKorisnici);
        mtp1.refresujPodatke();
        ModelTabeleProdavac mtp2 = (ModelTabeleProdavac) jTablePovezaniKorisnici.getModel();
        mtp2.setProdavci(povezaniKorisnici);
        mtp2.refresujPodatke();
       
       osveziTabele();
       
       
       
       
    }//GEN-LAST:event_jButtonPokreniServerActionPerformed

    private void jButtonZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZaustaviServerActionPerformed
        
        ps.zaustaviServer();
        jLabelStatus.setText("SERVER JE ZAUSTAVLJEN");
        jButtonPokreniServer.setEnabled(true);
        jButtonZaustaviServer.setEnabled(false);
        nepovezaniKorisnici = new ArrayList<>();
        ModelTabeleProdavac mti1 = (ModelTabeleProdavac) jTableNepovezaniKorisnici.getModel();
        mti1.setProdavci(nepovezaniKorisnici);
        mti1.refresujPodatke();
        ModelTabeleProdavac mti2 = (ModelTabeleProdavac) jTablePovezaniKorisnici.getModel();
        List<Prodavac> povezaniKorisnici1 = new ArrayList<>();
        mti2.setProdavci(povezaniKorisnici1);
        mti2.refresujPodatke();
    }//GEN-LAST:event_jButtonZaustaviServerActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        fk = new FormaKonfiguracija(this,true);
        fk.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPokreniServer;
    private javax.swing.JButton jButtonZaustaviServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableNepovezaniKorisnici;
    private javax.swing.JTable jTablePovezaniKorisnici;
    // End of variables declaration//GEN-END:variables

private void popuniTabeluPovezani() {
        List<Prodavac> povezaniProdavci1 = new ArrayList<>();

        ModelTabeleProdavac mtp = new ModelTabeleProdavac(povezaniProdavci1);
        jTablePovezaniKorisnici.setModel(mtp);
        mtp.refresujPodatke();
    }

    private void popuniTabeluNepovezani() {
        ModelTabeleProdavac mtp = new ModelTabeleProdavac(nepovezaniKorisnici);
        jTableNepovezaniKorisnici.setModel(mtp);
        mtp.refresujPodatke();
    }

    public void osveziTabele() {

       try {
            sviKorisnici = Kontroler.getInstance().vratiListuSvihProdavaca();
        } catch (Exception ex) {
            System.err.println("Sistem ne može da učita prodavce iz baze.");
        }
        nepovezaniKorisnici = new ArrayList<>();
        List<Prodavac> povezaniKorisnici = new ArrayList<>();
        for (ObradaKlijentskihZahteva korisnik : ServerskaNit.getPrijavljeniKorisnici()) {
            Prodavac p = new Prodavac(korisnik.getIme(), korisnik.getPrezime(), korisnik.getKorisnickoIme(), korisnik.getSifra(), korisnik.getEmail());
            povezaniKorisnici.add(p);
        }
        for (Prodavac p : sviKorisnici) {
            if (!povezaniKorisnici.contains(p)) {
                nepovezaniKorisnici.add(p);
            }
        }
        ModelTabeleProdavac mti1 = (ModelTabeleProdavac) jTableNepovezaniKorisnici.getModel();
        mti1.setProdavci(nepovezaniKorisnici);
        mti1.refresujPodatke();
        ModelTabeleProdavac mtp2 = (ModelTabeleProdavac) jTablePovezaniKorisnici.getModel();
        mtp2.setProdavci(povezaniKorisnici);
        mtp2.refresujPodatke();
        
    }

 public void dizajn() {
    // POZADINA forme – svetla siva
    getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // #F5F5F5

    this.setSize(700, 700); 
    this.setLocationRelativeTo(null); 
    this.setResizable(false);

    // DUGMAD – tamno maslinasto zelena
    jButtonPokreniServer.setBackground(new java.awt.Color(46, 78, 31)); // #2E4E1F
    jButtonPokreniServer.setForeground(Color.WHITE);

    jButtonZaustaviServer.setBackground(new java.awt.Color(46, 78, 31)); // #2E4E1F
    jButtonZaustaviServer.setForeground(Color.WHITE);

    // FONTOVI
    Font meniFont = new Font("Times New Roman", Font.BOLD, 18);
    Font tabelaFont = new Font("Times New Roman", Font.PLAIN, 16); 
    Font dugmeFont = new Font("Times New Roman", Font.BOLD, 14);

    // MENI
    jMenuBar1.setFont(meniFont);
    jMenu1.setFont(meniFont);
    jMenuItem4.setFont(meniFont);
    jMenuBar1.setBackground(new java.awt.Color(46, 78, 31)); // #2E4E1F
    jMenu1.setForeground(Color.WHITE);

    // TABELE
    jTablePovezaniKorisnici.setFont(tabelaFont);
    jTablePovezaniKorisnici.setRowHeight(24); 
    jTablePovezaniKorisnici.setBackground(Color.WHITE);
    jTablePovezaniKorisnici.setForeground(new java.awt.Color(43, 43, 43)); // #2B2B2B
    jTablePovezaniKorisnici.setGridColor(new java.awt.Color(204, 204, 204)); // #CCCCCC

    jTableNepovezaniKorisnici.setFont(tabelaFont);
    jTableNepovezaniKorisnici.setRowHeight(24);
    jTableNepovezaniKorisnici.setBackground(Color.WHITE);
    jTableNepovezaniKorisnici.setForeground(new java.awt.Color(43, 43, 43));
    jTableNepovezaniKorisnici.setGridColor(new java.awt.Color(204, 204, 204));

    // HEADER tabele – tamno maslinasta
    Font headerFont = new Font("Times New Roman", Font.BOLD, 16);
    jTablePovezaniKorisnici.getTableHeader().setFont(headerFont);
    jTablePovezaniKorisnici.getTableHeader().setBackground(new java.awt.Color(59, 83, 35)); // #3B5323
    jTablePovezaniKorisnici.getTableHeader().setForeground(Color.WHITE);

    jTableNepovezaniKorisnici.getTableHeader().setFont(headerFont);
    jTableNepovezaniKorisnici.getTableHeader().setBackground(new java.awt.Color(59, 83, 35));
    jTableNepovezaniKorisnici.getTableHeader().setForeground(Color.WHITE);
}



       




}
