/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

import java.io.Serializable;

/**
 *
 * @author Ljilja
 */
public enum Operacije implements Serializable {
    UCITAJ_SVE_KNJIGE, OBRISI_KNJIGU, KREIRAJ_KNJIGU, VRATI_SVE_PRODAVCE, 
    VRATI_KNJIGU, PROMENI_KNJIGU, KREIRAJ_MESTO, VRATI_SVA_MESTA, KREIRAJ_KUPCA, 
    PRETRAZI_MESTO, PROMENI_MESTO, OBRISI_MESTO, VRATI_LISTU_MESTA, PRETRAZI_KNJIGU, VRATI_SVE_STR_SPREMA,VRATI_SVE_KUPAC, 
    
    PRETRAZI_KUPCA, PROMENI_KUPCA, OBRISI_KUPCA, VRATI_KUPCE_KUPAC, VRATI_KUPCE_MESTO, ODJAVI_PRODAVCA, VRATI_KNJIGE_KNJIGA, 
    UBACI_STR_SPREMU, PRETRAZI_STR_SPREMU, OBRISI_STR_SPREMU, PROMENI_STR_SPREMU, VRATI_STR_SPREME_STR_SPREMA, 
    KREIRAJ_PRODAVCA, OBRISI_PRODAVCA, PRETRAZI_PRODAVCA, PROMENI_PRODAVCA, VRATI_LISTU_SVI_PRODAVAC, VRATI_PRODAVCI_PRODAVAC,
    VRATI_PRODAVCI_STR_SPREMA,
    KREIRAJ_RACUN, PROMENI_RACUN, PRETRAZI_RACUN, VRATI_LISTU_SVI_RACUN, VRATI_LISTU_RACUN_RACUN, VRATI_LISTU_RACUN_PRODAVAC,
    VRATI_LISTU_RACUN_KUPAC, VRATI_LISTU_RACUN_KNJIGA, PRIJAVI_PRODAVCA, DODAJ_PRIJAVLJENOG, UCITAJ_SVE_MAGACINE, 
}
